const weeks=[["Week 1", "Start here", "Set up your workspace and goals."], ["Week 2", "Foundations", "Build the core skills and vocabulary."], ["Week 3", "Practice", "Keep your existing work and strengthen the basics."], ["Week 4", "Connect, change, explain", "JavaScript, connections, and your 3D page."], ["Week 5", "Explore", "Apply the ideas to your own subject."], ["Week 6", "Build", "Create and test a useful feature."], ["Week 7", "Refine", "Review what works and improve it."], ["Week 8", "Checkpoint", "Organize your work and record progress."], ["Week 9", "Research", "Gather and organize supporting material."], ["Week 10", "Create", "Turn your research into a working project."], ["Week 11", "Test", "Try controlled changes and document results."], ["Week 12", "Explain", "Make your work understandable to visitors."], ["Week 13", "Design", "Improve structure, layout, and navigation."], ["Week 14", "Connect", "Link related pages and resources."], ["Week 15", "Review", "Check details and correct problems."], ["Week 16", "Polish", "Improve accessibility and responsive layout."], ["Week 17", "Share", "Prepare the complete published folder."], ["Week 18", "Feedback", "Use observations to make corrections."], ["Week 19", "Final checks", "Test links, pages, layout, and interactions."], ["Week 20", "Finish", "Complete your final review and publish."]];const grid=document.getElementById("weekGrid");
function renderWeeks(q=""){grid.innerHTML=weeks.map((w,i)=>q&&!w.join(" ").toLowerCase().includes(q.toLowerCase())?"":`<a class="week-card ${i===3?"current":""}" href="weeks/week-${i+1}.html"><span class="week-no">${w[0]}</span><h3>${w[1]}</h3><p>${w[2]}</p></a>`).join("")}
renderWeeks();document.getElementById("weekSearch").oninput=e=>renderWeeks(e.target.value);
const esc=s=>s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
let tasks=JSON.parse(localStorage.getItem("studyTasks")||"[]"),list=document.getElementById("taskList");
function drawTasks(){list.innerHTML=tasks.map((t,i)=>`<li>${esc(t)}<button onclick="removeTask(${i})">×</button></li>`).join("");localStorage.setItem("studyTasks",JSON.stringify(tasks))}
document.getElementById("addTask").onclick=()=>{let x=document.getElementById("taskInput");if(x.value.trim()){tasks.push(x.value.trim());x.value="";drawTasks()}};window.removeTask=i=>{tasks.splice(i,1);drawTasks()};drawTasks();
let sec=1500,id=null,timer=document.getElementById("timer");function show(){timer.textContent=`${String(Math.floor(sec/60)).padStart(2,"0")}:${String(sec%60).padStart(2,"0")}`}
document.getElementById("startTimer").onclick=()=>{if(id)return;id=setInterval(()=>{sec--;show();if(sec<=0){clearInterval(id);id=null;alert("Focus session complete!")}},1000)};document.getElementById("resetTimer").onclick=()=>{clearInterval(id);id=null;sec=1500;show()};show();
let notes=document.getElementById("notes");notes.value=localStorage.getItem("studyNotes")||"";notes.oninput=()=>{localStorage.setItem("studyNotes",notes.value);document.getElementById("saveStatus").textContent="Saved just now"};
let links=JSON.parse(localStorage.getItem("quickLinks")||JSON.stringify([["MDN","https://developer.mozilla.org/"],["YouTube","https://www.youtube.com/"],["Google","https://www.google.com/"],["GitHub","https://github.com/"]]));const lg=document.getElementById("linkGrid");
function drawLinks(){lg.innerHTML=links.map((l,i)=>`<a class="link-card" href="${l[1]}" target="_blank" rel="noopener"><button class="delete-link" onclick="event.preventDefault();event.stopPropagation();links.splice(${i},1);drawLinks()">×</button><div>↗</div><h3>${esc(l[0])}</h3><p>${esc(l[1])}</p></a>`).join("");localStorage.setItem("quickLinks",JSON.stringify(links))}
document.getElementById("addLink").onclick=()=>{let m=document.createElement("div");m.className="modal";m.innerHTML='<div class="modal-box"><h3>Add a website</h3><div class="link-form"><input id="ln" placeholder="Website name"><input id="lu" placeholder="https://example.com"></div><div class="modal-actions"><button id="cancel">Cancel</button><button class="save" id="save">Add website</button></div></div>';document.body.appendChild(m);m.querySelector("#cancel").onclick=()=>m.remove();m.querySelector("#save").onclick=()=>{let n=m.querySelector("#ln").value.trim(),u=m.querySelector("#lu").value.trim();if(n&&/^https?:\/\//i.test(u)){links.push([n,u]);drawLinks();m.remove()}else alert("Enter a name and a full URL.")};m.querySelector("#ln").focus()};drawLinks();

// Week 4 local Babylon scene
if(window.BABYLON&&document.getElementById('renderCanvas')){const c=document.getElementById('renderCanvas'),e=new BABYLON.Engine(c,true),s=new BABYLON.Scene(e),cam=new BABYLON.ArcRotateCamera('camera',-Math.PI/2,Math.PI/3,7,BABYLON.Vector3.Zero(),s);cam.attachControl(c,true);new BABYLON.HemisphericLight('light',new BABYLON.Vector3(0,1,0),s);BABYLON.MeshBuilder.CreateGround('ground',{width:8,height:8},s);const sp=BABYLON.MeshBuilder.CreateSphere('sphere',{diameter:2,segments:32},s);sp.position.y=1;e.runRenderLoop(()=>s.render());window.addEventListener('resize',()=>e.resize());const st=document.getElementById('scene-status');if(st)st.textContent='Interactive Week 4 scene ready.';const rb=document.getElementById('reset-view');if(rb){rb.disabled=false;rb.onclick=()=>cam.setPosition(new BABYLON.Vector3(-4,3,4))}}
